apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: azure-cli-template-create-storage
  description: Azure CLI template to create a storage account
spec:
  type: cli-template
  owner: cloud-team
  system: azure
  parameters:
    $text: |
      az storage account create \
        --name myteststg001 \
        --resource-group 1-6e8b95a3-playground-sandbox \
        --location SouthCentralUS \
        --sku Standard_LRS
